[package]
name = "ray_tracer_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.13.0"
palette = "0.6.0"
assert_approx_eq = "1.1.0"